# Generated by Django 4.2.26 on 2025-11-30 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0002_alter_people_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=datetime.datetime(2025, 11, 30, 23, 59, 56, 653148, tzinfo=datetime.timezone.utc)),
        ),
    ]
