# Generated by Django 6.0 on 2026-01-06 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0003_alter_people_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=datetime.datetime(2026, 1, 6, 16, 41, 48, 83932, tzinfo=datetime.timezone.utc)),
        ),
    ]
