# Generated by Django 6.0 on 2026-01-08 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0004_alter_people_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=datetime.datetime(2026, 1, 8, 11, 2, 31, 108748, tzinfo=datetime.timezone.utc)),
        ),
    ]
