# Generated by Django...

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone # Import nécessaire pour la date

class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0005_alter_people_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(
                db_column='homeworld', 
                on_delete=django.db.models.deletion.CASCADE, 
                to='ex09.planets', 
                to_field='name'
            ),
        ),
        migrations.AlterField(
            model_name='people',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='climate',
            field=models.TextField(null=True), # Remis en TextField pour être safe
        ),
    ]