# Generated by Django 6.0.1 on 2026-01-08 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0006_alter_people_created_alter_people_homeworld_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(db_column='homeworld', null=True, on_delete=django.db.models.deletion.CASCADE, to='ex09.planets', to_field='name'),
        ),
        migrations.AlterField(
            model_name='planets',
            name='climate',
            field=models.CharField(null=True),
        ),
    ]
