# Generated by Django 6.0 on 2026-01-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='opening_crawl',
            field=models.TextField(null=True),
        ),
    ]
