# Generated by Django 6.0 on 2025-12-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='synonpsis',
        ),
    ]
