# Generated by Django 6.0 on 2025-12-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_synonpsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='synopsis',
            field=models.CharField(default='mdr', max_length=312),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
