# Generated by Django 5.2.8 on 2025-12-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tip',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
