# Generated by Django 5.2.8 on 2025-12-03 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_tip_downvotes_tip_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='tip',
            name='downvotes',
            field=models.ManyToManyField(related_name='downvoted_tips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tip',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvoted_tips', to=settings.AUTH_USER_MODEL),
        ),
    ]
