# Generated by Django 5.2.8 on 2025-12-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_remove_tip_downvotes_remove_tip_upvotes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'permissions': [('candownvote', 'Can downvote tips')]},
        ),
    ]
