# Generated by Django 5.2.8 on 2025-12-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0005_alter_tip_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
