# Generated by Django 5.2.8 on 2025-12-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0006_tip_reputation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='reputation',
        ),
        migrations.AddField(
            model_name='customuser',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
